//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prova1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public int Id { get; set; }
        public int Funcionario_Id { get; set; }
        public int Supervisor_Id { get; set; }
        public int Cargo_Id { get; set; }
        public System.DateTime Horario { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Funcionario Funcionario1 { get; set; }
    }
}
